project: "AUTH-HUB DEMO"
version: "0.0.1"
author: "IndustryBuilders Team"
login:
  user: 
    value: "username"
    disabled: true
  sns: 
    value: "sns"
    disabled: true
  oidc:
    value: "oidc"
    providers:
      - name: "authing"
        label: "Authing"
        # description: "Authentication service for ensuring application security"
        clientId: "66b769cf5c2d439dfd37f237"
        redirectUri: "https://demo-center.authing.cn"
      - name: "keycloak"
        label: "Keycloak"
        # description: "Open Source Identity and Access Management"
        clientId: "668d3fa8e264cf3675dcc42a"
        redirectUri: "https://intelli-agent.authing.cn"
        diabled: true
      - name: cognito
        label: Cognito
        client_id: 6fsdfdsdddddsadsf434ssd3
        user_pool_id: us-east-1_VeItKBhLQ
        # client_secret: fasded3442324dfsd8632sddsa
        domain: us-east-1veitkbhlq.auth.us-east-1.amazoncognito.com
        region: us-east-1
  sso:
    midway:
      - cognito_user_pool_id: us-east-1_VeItKBhLQ
      - cognito_user_pool_client_id: 4sp7uqbhmd3sos5efhnm9bra2e
      - cognito_domain: us-east-1veitkbhlq.auth.us-east-1.amazoncognito.com
      - provider_name: provider
      # - scopes:
      #   - openid
      #   - email
      #   - profile
      #   - aws.cognito.signin.user.admin
      # - redirect_sign_in: ""
      # - redirect_sign_out: ""
      # - response_type: code

  # third:
  #   - type: "google"
  #     iconUrlSelected: "google_in"
  #     iconUrl: "google"
  #     iconStyle: {"width":39,"marginTop":-2}
  #   - type: "facebook"
  #     iconUrlSelected: "facebook_in"
  #     iconUrl: "facebook"
  #     iconStyle: {"width":34}
  #   - type: "linkedin"
  #     iconUrlSelected: "linkedin_in"
  #     iconUrl: "linkedin"
  #     iconStyle: {"width":35}
  