project: "Auth Hub Demo"
version: "0.0.1"
author: "IndustryBuilders Team"
login:
  user: 
    value: "username"
    disabled: true
  sns: 
    value: "sns"
    disabled: true
  oidc:
    value: "oidc"
    providers:
      # hint: If Cognito is configured here, the system will use the configuration information provided here.
      # - name: "cognito"
      #   label: "Cognito"
      #   description: "AWS's built-in user authentication service"
      #   clientId: "1ni02jacoqjo2tn1ier69cebb7"  
      #   userPoolId: "us-east-1_PaWe18vwE"
      #   redirectUri: "https://demo-authingrandom-mvjzq.auth.us-east-1.amazoncognito.com"
      - name: "authing"
        label: "Authing"
        # description: "Authentication service for ensuring application security"
        clientId: "66b769cf5c2d439dfd37f237"
        redirectUri: "https://demo-center.authing.cn"
      - name: "keycloak"
        label: "Keycloak"
        # description: "Open Source Identity and Access Management"
        clientId: "668d3fa8e264cf3675dcc42a"
        redirectUri: "https://intelli-agent.authing.cn"
        diabled: true
  third:
    - type: "google"
      iconUrlSelected: "google_in"
      iconUrl: "google"
      iconStyle: {"width":39,"marginTop":-2}
    - type: "facebook"
      iconUrlSelected: "facebook_in"
      iconUrl: "facebook"
      iconStyle: {"width":34}
    - type: "linkedin"
      iconUrlSelected: "linkedin_in"
      iconUrl: "linkedin"
      iconStyle: {"width":35}
  